mode: rule
mixed-port: 7897
allow-lan: true
log-level: info
ipv6: true
external-controller: 0.0.0.0:9097
secret: ''
unified-delay: true
dns:
  default-nameserver:
  - system
  - 223.6.6.6
  - 8.8.8.8
  - 2400:3200::1
  - 2001:4860:4860::8888
  direct-nameserver: []
  direct-nameserver-follow-policy: false
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.arpa'
  - time.*.com
  - ntp.*.com
  - time.*.com
  - +.market.xiaomi.com
  - localhost.ptlogin2.qq.com
  - '*.msftncsi.com'
  - www.msftconnecttest.com
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fallback: []
  fallback-filter:
    domain:
    - +.google.com
    - +.facebook.com
    - +.youtube.com
    geoip: true
    geoip-code: CN
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
  ipv6: true
  listen: 0.0.0.0:53
  nameserver:
  - 8.8.8.8
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  prefer-h3: false
  proxy-server-nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  - tls://223.5.5.5
  respect-rules: false
  use-hosts: false
  use-system-hosts: false
external-controller-unix: /tmp/verge/verge-mihomo.sock
profile:
  store-selected: true
ntp:
  enable: true
  write-to-system: false
  server: ntp.tencent.com
  port: 123
  interval: 30
bind-address: '*'
tcp-concurrent: true
keep-alive-interval: 360
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Mihomo
  dns-hijack:
  - any:53
  mtu: 1500
  route-exclude-address: []
  stack: system
  strict-route: false
  enable: true
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - tauri://localhost
  - http://tauri.localhost
  - https://yacd.metacubex.one
  - https://metacubex.github.io
  - https://board.zash.run.place
clash-for-android:
  append-system-dns: false

proxy-providers:
  provider0:
    type: http
    path: ./providers/provider0.yaml
    url: <PROVIDER0_URL>
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
    proxy: DIRECT

proxy-groups:
- name: PROXY
  type: select
  include-all: true
  proxies:
  - AUTO
  - FALLBACK
  - VIP2
  - AI

- name: AUTO
  type: url-test
  include-all: true
  url: https://www.gstatic.com/generate_204
  interval: 300
  lazy: true

- name: FALLBACK
  type: fallback
  include-all: true
  url: https://www.gstatic.com/generate_204
  interval: 300
  lazy: true

- name: VIP2
  type: url-test
  interval: 300
  lazy: true
  url: https://www.gstatic.com/generate_204
  filter: VIP2
  include-all: true

- name: AI
  type: url-test
  interval: 300
  lazy: true
  url: https://www.gstatic.com/generate_204
  filter: 新加坡-VIP2
  include-all: true

rule-providers:
  # https://github.com/Loyalsoldier/clash-rules
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  # https://github.com/SkywalkerJi/Clash-Rules/tree/master/AI
  anthropic:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/SkywalkerJi/Clash-Rules/master/AI/Anthropic.yaml"
    path: ./ruleset/anthropic.yaml
    interval: 86400

  openai:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/SkywalkerJi/Clash-Rules/master/AI/OpenAI.yaml"
    path: ./ruleset/openai.yaml
    interval: 86400

  gemini:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/SkywalkerJi/Clash-Rules/master/AI/Gemini.yaml"
    path: ./ruleset/gemini.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,anthropic,AI
  - RULE-SET,openai,AI
  - RULE-SET,gemini,AI
  - RULE-SET,google,PROXY
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,telegramcidr,PROXY
  - MATCH,DIRECT
